/**
 * WealthCraft Financial Calculators Engine
 * Includes SIP, SWP, Lumpsum, Loan (with Moratorium & Prepayments), and Goal Planner.
 */

document.addEventListener('DOMContentLoaded', () => {
  initNavigation();
  initSyncControls();
  initCalculators();
});

// Global chart instances tracker
const charts = {};

/**
 * 1. NAVIGATION & TAB SWITCHING
 */
function initNavigation() {
  const navItems = document.querySelectorAll('.nav-item');
  const views = document.querySelectorAll('.calculator-view');
  const currentTitle = document.getElementById('current-calc-title');
  const currentDesc = document.getElementById('current-calc-desc');

  const calcMetadata = {
    sip: {
      title: 'Systematic Investment Plan (SIP) Calculator',
      desc: 'Estimate the wealth generated by your monthly mutual fund or stock investments over time.'
    },
    swp: {
      title: 'Systematic Withdrawal Plan (SWP) Calculator',
      desc: 'Calculate how long your retirement corpus will last with recurring monthly withdrawals, taking inflation and growth into account.'
    },
    lumpsum: {
      title: 'Lumpsum Investment Calculator',
      desc: 'Calculate the future value of your one-time investments with nominal and inflation-adjusted projections.'
    },
    loan: {
      title: 'Loan & Education Loan EMI Calculator',
      desc: 'Calculate your EMI, analyze the amortization schedule, explore prepayments, and factor in student loan moratoriums.'
    },
    goal: {
      title: 'Goal Planner & Retirement Calculator',
      desc: 'Find out exactly how much you need to save monthly to achieve your future financial targets, adjusted for inflation.'
    }
  };

  navItems.forEach(item => {
    const button = item.querySelector('button');
    button.addEventListener('click', () => {
      const targetViewId = button.getAttribute('data-target');
      
      // Update active nav class
      navItems.forEach(nav => nav.classList.remove('active'));
      item.classList.add('active');

      // Update views visibility
      views.forEach(view => {
        if (view.id === targetViewId) {
          view.classList.add('active');
        } else {
          view.classList.remove('active');
        }
      });

      // Update headers
      const metadata = calcMetadata[targetViewId];
      if (metadata) {
        currentTitle.textContent = metadata.title;
        currentDesc.textContent = metadata.desc;
      }

      // Execute calculation for newly selected calculator
      runCalculator(targetViewId);
    });
  });
}

/**
 * 2. SYNC RANGE SLIDERS AND NUMERIC INPUTS
 */
function initSyncControls() {
  // Select all form-groups to find corresponding slider and number inputs
  const syncPairs = [
    // SIP inputs
    { num: 'sip-amt', slider: 'sip-amt-range' },
    { num: 'sip-rate', slider: 'sip-rate-range' },
    { num: 'sip-years', slider: 'sip-years-range' },
    { num: 'sip-stepup', slider: 'sip-stepup-range' },
    { num: 'sip-inflation', slider: 'sip-inflation-range' },
    
    // SWP inputs
    { num: 'swp-corpus', slider: 'swp-corpus-range' },
    { num: 'swp-withdrawal', slider: 'swp-withdrawal-range' },
    { num: 'swp-rate', slider: 'swp-rate-range' },
    { num: 'swp-years', slider: 'swp-years-range' },
    { num: 'swp-inflation', slider: 'swp-inflation-range' },
    { num: 'swp-stepup', slider: 'swp-stepup-range' },

    // Lumpsum inputs
    { num: 'lump-amt', slider: 'lump-amt-range' },
    { num: 'lump-rate', slider: 'lump-rate-range' },
    { num: 'lump-years', slider: 'lump-years-range' },
    { num: 'lump-inflation', slider: 'lump-inflation-range' },

    // Loan inputs
    { num: 'loan-amt', slider: 'loan-amt-range' },
    { num: 'loan-rate', slider: 'loan-rate-range' },
    { num: 'loan-years', slider: 'loan-years-range' },
    { num: 'loan-moratorium', slider: 'loan-moratorium-range' },
    { num: 'loan-prepayment', slider: 'loan-prepayment-range' },

    // Goal Planner inputs
    { num: 'goal-target', slider: 'goal-target-range' },
    { num: 'goal-years', slider: 'goal-years-range' },
    { num: 'goal-rate', slider: 'goal-rate-range' },
    { num: 'goal-inflation', slider: 'goal-inflation-range' },
    { num: 'goal-stepup', slider: 'goal-stepup-range' },
  ];

  syncPairs.forEach(pair => {
    const numInput = document.getElementById(pair.num);
    const sliderInput = document.getElementById(pair.slider);

    if (numInput && sliderInput) {
      // Sync slider to number input
      sliderInput.addEventListener('input', () => {
        numInput.value = sliderInput.value;
        triggerCalculation(pair.num);
      });

      // Sync number input to slider
      numInput.addEventListener('input', () => {
        // Validate input range before updates
        const min = parseFloat(sliderInput.min);
        const max = parseFloat(sliderInput.max);
        let val = parseFloat(numInput.value) || 0;

        if (val < min) val = min;
        if (val > max) val = max;

        sliderInput.value = val;
        triggerCalculation(pair.num);
      });
    }
  });

  // Toggles that show/hide advanced settings
  const toggles = [
    { toggle: 'sip-stepup-toggle', panel: 'sip-stepup-panel' },
    { toggle: 'sip-inflation-toggle', panel: 'sip-inflation-panel' },
    { toggle: 'swp-inflation-toggle', panel: 'swp-inflation-panel' },
    { toggle: 'swp-stepup-toggle', panel: 'swp-stepup-panel' },
    { toggle: 'loan-advanced-toggle', panel: 'loan-advanced-panel' },
  ];

  toggles.forEach(t => {
    const checkbox = document.getElementById(t.toggle);
    const panel = document.getElementById(t.panel);

    if (checkbox && panel) {
      checkbox.addEventListener('change', () => {
        if (checkbox.checked) {
          panel.classList.add('show');
        } else {
          panel.classList.remove('show');
          // Reset internal values when hidden to keep calculations simple
          const input = panel.querySelector('input[type="number"]');
          const slider = panel.querySelector('input[type="range"]');
          if (input && slider) {
            input.value = 0;
            slider.value = 0;
          }
        }
        // Recalculate
        const activeView = document.querySelector('.calculator-view.active');
        if (activeView) runCalculator(activeView.id);
      });
    }
  });
}

function triggerCalculation(inputId) {
  // Figure out which calculator view this input belongs to
  if (inputId.startsWith('sip-')) {
    runCalculator('sip');
  } else if (inputId.startsWith('swp-')) {
    runCalculator('swp');
  } else if (inputId.startsWith('lump-')) {
    runCalculator('lumpsum');
  } else if (inputId.startsWith('loan-')) {
    runCalculator('loan');
  } else if (inputId.startsWith('goal-')) {
    runCalculator('goal');
  }
}

/**
 * 3. CORE CALCULATOR ROUTER
 */
function initCalculators() {
  // Run all calculations once at startup
  runCalculator('sip');
  runCalculator('swp');
  runCalculator('lumpsum');
  runCalculator('loan');
  runCalculator('goal');
}

function runCalculator(id) {
  switch (id) {
    case 'sip':
      calcSIP();
      break;
    case 'swp':
      calcSWP();
      break;
    case 'lumpsum':
      calcLumpsum();
      break;
    case 'loan':
      calcLoan();
      break;
    case 'goal':
      calcGoal();
      break;
  }
}

/**
 * 4. FINANCIAL FORMULAS & RENDER FUNCTIONS
 */

// Helper to format currency (INR style formatting is standard, but simple universal formatting works)
function formatCurrency(amount) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0
  }).format(amount);
}

// Format percent
function formatPercent(val) {
  return `${parseFloat(val).toFixed(2)}%`;
}

/**
 * A. SIP Calculator
 */
function calcSIP() {
  const principal = parseFloat(document.getElementById('sip-amt').value) || 0;
  const annualRate = parseFloat(document.getElementById('sip-rate').value) || 0;
  const years = parseFloat(document.getElementById('sip-years').value) || 0;
  
  const stepUpToggle = document.getElementById('sip-stepup-toggle').checked;
  const stepUpPercent = stepUpToggle ? parseFloat(document.getElementById('sip-stepup').value) || 0 : 0;
  
  const inflationToggle = document.getElementById('sip-inflation-toggle').checked;
  const inflationRate = inflationToggle ? parseFloat(document.getElementById('sip-inflation').value) || 0 : 0;

  const totalMonths = years * 12;
  const monthlyRate = annualRate / 12 / 100;

  let totalInvested = 0;
  let futureValue = 0;
  let currentMonthlySIP = principal;

  const monthlyInvestments = [];
  const monthlyBalances = [];
  const months = [];

  for (let m = 1; m <= totalMonths; m++) {
    // If it's a new year and step-up is active (and not the first month of Year 1)
    if (stepUpToggle && m > 1 && (m - 1) % 12 === 0) {
      currentMonthlySIP = currentMonthlySIP * (1 + stepUpPercent / 100);
    }

    // Standard SIP compound addition (start of month deposit)
    totalInvested += currentMonthlySIP;
    futureValue = (futureValue + currentMonthlySIP) * (1 + monthlyRate);

    // Save history monthly for charts (aggregate yearly or select points to avoid clogging)
    if (m % 12 === 0 || m === totalMonths) {
      months.push(`Yr ${m / 12}`);
      monthlyInvestments.push(Math.round(totalInvested));
      monthlyBalances.push(Math.round(futureValue));
    }
  }

  // Inflation adjusted future value
  const inflationAdjustmentFactor = Math.pow(1 + inflationRate / 100, years);
  const inflationAdjustedFV = futureValue / inflationAdjustmentFactor;
  const wealthGained = Math.max(0, futureValue - totalInvested);

  // Update UI values
  document.getElementById('sip-kpi-invested').textContent = formatCurrency(totalInvested);
  document.getElementById('sip-kpi-wealth').textContent = formatCurrency(wealthGained);
  document.getElementById('sip-kpi-total').textContent = formatCurrency(futureValue);
  document.getElementById('sip-kpi-adjusted').textContent = inflationToggle ? formatCurrency(inflationAdjustedFV) : 'N/A';

  // Toggle adjusted row display
  const adjustedKpiCard = document.getElementById('sip-adjusted-card');
  if (inflationToggle) {
    adjustedKpiCard.style.display = 'block';
  } else {
    adjustedKpiCard.style.display = 'none';
  }

  // Render SIP Chart
  renderDoughnutChart('sip-chart', ['Invested Amount', 'Wealth Gained'], [totalInvested, wealthGained], ['#818cf8', '#34d399']);
  
  // Render schedule table
  let tableHtml = `
    <table>
      <thead>
        <tr>
          <th>Year</th>
          <th>Monthly SIP</th>
          <th>Total Invested</th>
          <th>Estimated Value</th>
          <th>Wealth Gained</th>
        </tr>
      </thead>
      <tbody>
  `;

  let currentSIP = principal;
  let cumInvested = 0;
  let tempFV = 0;

  for (let y = 1; y <= years; y++) {
    let yearInvestment = 0;
    for (let m = 1; m <= 12; m++) {
      cumInvested += currentSIP;
      tempFV = (tempFV + currentSIP) * (1 + monthlyRate);
    }

    tableHtml += `
      <tr>
        <td>Year ${y}</td>
        <td>${formatCurrency(currentSIP)}</td>
        <td>${formatCurrency(cumInvested)}</td>
        <td>${formatCurrency(tempFV)}</td>
        <td>${formatCurrency(tempFV - cumInvested)}</td>
      </tr>
    `;

    if (stepUpToggle) {
      currentSIP = currentSIP * (1 + stepUpPercent / 100);
    }
  }

  tableHtml += `</tbody></table>`;
  document.getElementById('sip-table').innerHTML = tableHtml;
}

/**
 * B. SWP Calculator
 */
function calcSWP() {
  const initialCorpus = parseFloat(document.getElementById('swp-corpus').value) || 0;
  const initialWithdrawal = parseFloat(document.getElementById('swp-withdrawal').value) || 0;
  const annualRate = parseFloat(document.getElementById('swp-rate').value) || 0;
  const years = parseFloat(document.getElementById('swp-years').value) || 0;

  const inflationToggle = document.getElementById('swp-inflation-toggle').checked;
  const inflationRate = inflationToggle ? parseFloat(document.getElementById('swp-inflation').value) || 0 : 0;

  const stepUpToggle = document.getElementById('swp-stepup-toggle').checked;
  const stepUpRate = stepUpToggle ? parseFloat(document.getElementById('swp-stepup').value) || 0 : 0;

  const monthlyRate = annualRate / 12 / 100;
  const totalMonths = years * 12;

  let balance = initialCorpus;
  let totalWithdrawn = 0;
  let totalInterest = 0;
  let currentWithdrawal = initialWithdrawal;

  let exhaustedMonth = -1;
  const yearlyData = [];
  
  const chartLabels = ['Start'];
  const chartBalance = [initialCorpus];
  const chartWithdrawn = [0];

  let tempYearInvested = initialCorpus;
  let tempYearWithdrawn = 0;
  let tempYearInterest = 0;

  for (let m = 1; m <= totalMonths; m++) {
    // Annual increase in withdrawal rate due to Inflation and/or Step Up
    if (m > 1 && (m - 1) % 12 === 0) {
      let increaseMultiplier = 1;
      if (inflationToggle) increaseMultiplier *= (1 + inflationRate / 100);
      if (stepUpToggle) increaseMultiplier *= (1 + stepUpRate / 100);
      currentWithdrawal = currentWithdrawal * increaseMultiplier;
    }

    let withdrawnThisMonth = 0;
    let interestThisMonth = 0;

    if (balance > 0) {
      // Withdrawal is made at the start of the month
      if (balance >= currentWithdrawal) {
        withdrawnThisMonth = currentWithdrawal;
        balance -= withdrawnThisMonth;
      } else {
        withdrawnThisMonth = balance;
        balance = 0;
        if (exhaustedMonth === -1) exhaustedMonth = m;
      }

      // Interest earned on the remaining balance during the month
      interestThisMonth = balance * monthlyRate;
      balance += interestThisMonth;

      totalWithdrawn += withdrawnThisMonth;
      totalInterest += interestThisMonth;

      tempYearWithdrawn += withdrawnThisMonth;
      tempYearInterest += interestThisMonth;
    } else {
      // Balance is already 0
      if (exhaustedMonth === -1) exhaustedMonth = m - 1;
    }

    // Store yearly data for table and charts
    if (m % 12 === 0 || m === totalMonths) {
      const yearIndex = Math.ceil(m / 12);
      yearlyData.push({
        year: yearIndex,
        withdrawalRate: currentWithdrawal,
        withdrawn: tempYearWithdrawn,
        interest: tempYearInterest,
        endingBalance: balance
      });

      chartLabels.push(`Yr ${yearIndex}`);
      chartBalance.push(Math.round(balance));
      chartWithdrawn.push(Math.round(totalWithdrawn));

      tempYearWithdrawn = 0;
      tempYearInterest = 0;
    }
  }

  // Update SWP Results KPIs
  document.getElementById('swp-kpi-withdrawn').textContent = formatCurrency(totalWithdrawn);
  document.getElementById('swp-kpi-interest').textContent = formatCurrency(totalInterest);
  document.getElementById('swp-kpi-remaining').textContent = formatCurrency(balance);

  // Render Exhaustion Alert Card
  const alertContainer = document.getElementById('swp-alert-container');
  if (exhaustedMonth !== -1) {
    const exhYears = Math.floor(exhaustedMonth / 12);
    const exhMonths = exhaustedMonth % 12;
    let durationText = '';
    if (exhYears > 0) durationText += `${exhYears} year${exhYears > 1 ? 's' : ''} `;
    if (exhMonths > 0) durationText += `${exhMonths} month${exhMonths > 1 ? 's' : ''}`;
    
    alertContainer.innerHTML = `
      <div class="alert alert-danger">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <div>
          <div class="alert-title">Corpus Exhaustion Warning</div>
          <div class="alert-description">Your wealth will be fully exhausted in <strong>${durationText}</strong> (after ${exhaustedMonth} months). Consider increasing returns, decreasing withdrawals, or lowering step-ups.</div>
        </div>
      </div>
    `;
  } else {
    alertContainer.innerHTML = `
      <div class="alert alert-success">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <div>
          <div class="alert-title">Corpus is Sustainable!</div>
          <div class="alert-description">Your retirement fund will easily last the entire <strong>${years} years</strong> tenure, leaving a residual balance of <strong>${formatCurrency(balance)}</strong>.</div>
        </div>
      </div>
    `;
  }

  // Draw Line Chart
  renderLineChart('swp-chart', chartLabels, [
    { label: 'Remaining Balance', data: chartBalance, color: '#4f46e5' },
    { label: 'Cumulative Withdrawals', data: chartWithdrawn, color: '#ef4444' }
  ]);

  // Render Table
  let tableHtml = `
    <table>
      <thead>
        <tr>
          <th>Year</th>
          <th>Monthly Withdrawal</th>
          <th>Total Withdrawn in Year</th>
          <th>Interest Earned in Year</th>
          <th>Ending Balance</th>
        </tr>
      </thead>
      <tbody>
  `;

  yearlyData.forEach(row => {
    const isExh = row.endingBalance <= 0 && row.withdrawn === 0;
    tableHtml += `
      <tr class="${isExh ? 'exhausted' : ''}">
        <td>Year ${row.year}</td>
        <td>${formatCurrency(row.withdrawalRate)}</td>
        <td>${formatCurrency(row.withdrawn)}</td>
        <td>${formatCurrency(row.interest)}</td>
        <td>${row.endingBalance > 0 ? formatCurrency(row.endingBalance) : '₹0 (Exhausted)'}</td>
      </tr>
    `;
  });

  tableHtml += `</tbody></table>`;
  document.getElementById('swp-table').innerHTML = tableHtml;
}

/**
 * C. Lumpsum Calculator
 */
function calcLumpsum() {
  const principal = parseFloat(document.getElementById('lump-amt').value) || 0;
  const annualRate = parseFloat(document.getElementById('lump-rate').value) || 0;
  const years = parseFloat(document.getElementById('lump-years').value) || 0;
  const inflationRate = parseFloat(document.getElementById('lump-inflation').value) || 0;

  const nominalValue = principal * Math.pow(1 + annualRate / 100, years);
  const inflationAdjustmentFactor = Math.pow(1 + inflationRate / 100, years);
  const realValue = nominalValue / inflationAdjustmentFactor;
  
  const wealthGained = Math.max(0, nominalValue - principal);
  const realWealthGained = Math.max(0, realValue - principal);

  // Update UI values
  document.getElementById('lump-kpi-invested').textContent = formatCurrency(principal);
  document.getElementById('lump-kpi-wealth').textContent = formatCurrency(wealthGained);
  document.getElementById('lump-kpi-total').textContent = formatCurrency(nominalValue);
  document.getElementById('lump-kpi-adjusted').textContent = formatCurrency(realValue);

  // Render Doughnut Chart
  renderDoughnutChart('lumpsum-chart', ['Principal Amount', 'Wealth Gained'], [principal, wealthGained], ['#818cf8', '#34d399']);

  // Render Table
  let tableHtml = `
    <table>
      <thead>
        <tr>
          <th>Year</th>
          <th>Estimated Value (Nominal)</th>
          <th>Total Wealth Gained</th>
          <th>Inflation Adjusted (Real Value)</th>
        </tr>
      </thead>
      <tbody>
  `;

  for (let y = 1; y <= years; y++) {
    const nomVal = principal * Math.pow(1 + annualRate / 100, y);
    const infVal = nomVal / Math.pow(1 + inflationRate / 100, y);
    tableHtml += `
      <tr>
        <td>Year ${y}</td>
        <td>${formatCurrency(nomVal)}</td>
        <td>${formatCurrency(nomVal - principal)}</td>
        <td>${formatCurrency(infVal)}</td>
      </tr>
    `;
  }

  tableHtml += `</tbody></table>`;
  document.getElementById('lumpsum-table').innerHTML = tableHtml;
}

/**
 * D. Loan / Education Loan EMI Calculator
 */
function calcLoan() {
  const principal = parseFloat(document.getElementById('loan-amt').value) || 0;
  const annualRate = parseFloat(document.getElementById('loan-rate').value) || 0;
  const years = parseFloat(document.getElementById('loan-years').value) || 0;
  
  const advancedToggle = document.getElementById('loan-advanced-toggle').checked;
  const moratoriumMonths = advancedToggle ? parseFloat(document.getElementById('loan-moratorium').value) || 0 : 0;
  const monthlyPrepayment = advancedToggle ? parseFloat(document.getElementById('loan-prepayment').value) || 0 : 0;

  const monthlyRate = annualRate / 12 / 100;
  
  // 1. Moratorium Phase: Interest accrues and is capitalized (added to principal)
  let capitalizedPrincipal = principal;
  let moratoriumInterestAccrued = 0;
  
  if (moratoriumMonths > 0) {
    // Interest compounded monthly during moratorium
    capitalizedPrincipal = principal * Math.pow(1 + monthlyRate, moratoriumMonths);
    moratoriumInterestAccrued = capitalizedPrincipal - principal;
  }

  // 2. Standard EMI Calculation on the Capitalized Principal
  const totalMonths = years * 12;
  let standardEmi = 0;
  
  if (capitalizedPrincipal > 0 && monthlyRate > 0) {
    standardEmi = capitalizedPrincipal * monthlyRate * Math.pow(1 + monthlyRate, totalMonths) / (Math.pow(1 + monthlyRate, totalMonths) - 1);
  } else if (years > 0) {
    standardEmi = capitalizedPrincipal / totalMonths;
  }

  // 3. Amortization simulation with Prepayments
  let balance = capitalizedPrincipal;
  let totalInterestPaid = moratoriumInterestAccrued;
  let totalAmountPaid = 0;
  let monthsCount = 0;

  const chartLabels = ['Start'];
  const chartBalance = [capitalizedPrincipal];
  const chartInterestPaid = [0];

  const yearlyAmortization = [];
  let tempYearPrincipal = 0;
  let tempYearInterest = 0;
  let tempYearPrepayment = 0;

  while (balance > 0.01 && monthsCount < 600) { // Limit to 50 years to prevent infinite loops
    monthsCount++;
    const interestThisMonth = balance * monthlyRate;
    
    // Standard payment + prepayment
    let payment = standardEmi + monthlyPrepayment;
    
    if (balance + interestThisMonth <= payment) {
      payment = balance + interestThisMonth;
    }

    const principalThisMonth = payment - interestThisMonth;
    balance = balance + interestThisMonth - payment;

    totalInterestPaid += interestThisMonth;
    totalAmountPaid += payment;

    tempYearPrincipal += principalThisMonth;
    tempYearInterest += interestThisMonth;
    if (payment > standardEmi) {
      tempYearPrepayment += (payment - standardEmi);
    }

    // Accumulate yearly data
    if (monthsCount % 12 === 0 || balance <= 0.01) {
      const yearIdx = Math.ceil(monthsCount / 12);
      yearlyAmortization.push({
        year: yearIdx,
        principalPaid: tempYearPrincipal,
        interestPaid: tempYearInterest,
        prepayment: tempYearPrepayment,
        endingBalance: Math.max(0, balance)
      });

      chartLabels.push(`Yr ${yearIdx}`);
      chartBalance.push(Math.round(Math.max(0, balance)));
      chartInterestPaid.push(Math.round(totalInterestPaid));

      tempYearPrincipal = 0;
      tempYearInterest = 0;
      tempYearPrepayment = 0;
    }
  }

  // 4. Calculate comparisons (interest saved)
  // We need to calculate what the loan cost WOULD be without prepayments
  let baselineTotalInterest = moratoriumInterestAccrued;
  if (capitalizedPrincipal > 0 && standardEmi > 0) {
    baselineTotalInterest += (standardEmi * totalMonths) - capitalizedPrincipal;
  }
  const interestSaved = Math.max(0, baselineTotalInterest - totalInterestPaid);
  const monthsSaved = Math.max(0, totalMonths - monthsCount);

  // Indirect Cost Indicator
  const totalCostMultiple = (totalAmountPaid / principal).toFixed(2);
  const costPercentage = ((totalInterestPaid / principal) * 100).toFixed(0);

  // Update UI values
  document.getElementById('loan-kpi-emi').textContent = formatCurrency(standardEmi);
  document.getElementById('loan-kpi-interest').textContent = formatCurrency(totalInterestPaid);
  document.getElementById('loan-kpi-total').textContent = formatCurrency(principal + totalInterestPaid);
  document.getElementById('loan-kpi-multiple').textContent = `${totalCostMultiple}x (${costPercentage}% Extra)`;

  // Show Advanced Warning/Comparison card if prepayment or moratorium is active
  const loanComparisonCard = document.getElementById('loan-comparison-card');
  const prepaymentInfo = document.getElementById('loan-prepayment-info');

  if (advancedToggle && (monthlyPrepayment > 0 || moratoriumMonths > 0)) {
    loanComparisonCard.style.display = 'block';
    
    let infoHtml = '';
    if (moratoriumMonths > 0) {
      infoHtml += `
        <div class="alert alert-warning" style="margin-bottom: 0.75rem;">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
          </svg>
          <div>
            <div class="alert-title">Interest Built Up During Grace Period</div>
            <div class="alert-description">The interest added during your <strong>${moratoriumMonths}-month</strong> study break is <strong>${formatCurrency(moratoriumInterestAccrued)}</strong>, which has been added to your original loan amount.</div>
          </div>
        </div>
      `;
    }
    
    if (monthlyPrepayment > 0 && monthsSaved > 0) {
      const savedYears = Math.floor(monthsSaved / 12);
      const savedMonths = monthsSaved % 12;
      let savedText = '';
      if (savedYears > 0) savedText += `${savedYears} year${savedYears > 1 ? 's' : ''} `;
      if (savedMonths > 0) savedText += `${savedMonths} month${savedMonths > 1 ? 's' : ''}`;

      infoHtml += `
        <div class="alert alert-success">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z" />
          </svg>
          <div>
            <div class="alert-title">Extra Payments Benefit!</div>
            <div class="alert-description">By paying an extra <strong>${formatCurrency(monthlyPrepayment)}/month</strong>, you will clear your loan <strong>${savedText} earlier</strong> and save <strong>${formatCurrency(interestSaved)}</strong> in interest charges!</div>
          </div>
        </div>
      `;
    }
    prepaymentInfo.innerHTML = infoHtml;
  } else {
    loanComparisonCard.style.display = 'none';
  }

  // Render Amortization Chart (Remaining Principal vs Paid Interest)
  renderLineChart('loan-chart', chartLabels, [
    { label: 'Remaining Loan Principal', data: chartBalance, color: '#4f46e5' },
    { label: 'Cumulative Interest Paid', data: chartInterestPaid, color: '#ef4444' }
  ]);

  // Render Table
  let tableHtml = `
    <table>
      <thead>
        <tr>
          <th>Year</th>
          <th>Principal Paid</th>
          <th>Interest Paid</th>
          <th>Extra Payments</th>
          <th>Ending Balance</th>
        </tr>
      </thead>
      <tbody>
  `;

  yearlyAmortization.forEach(row => {
    tableHtml += `
      <tr>
        <td>Year ${row.year}</td>
        <td>${formatCurrency(row.principalPaid)}</td>
        <td>${formatCurrency(row.interestPaid)}</td>
        <td>${row.prepayment > 0 ? formatCurrency(row.prepayment) : '₹0'}</td>
        <td>${formatCurrency(row.endingBalance)}</td>
      </tr>
    `;
  });

  tableHtml += `</tbody></table>`;
  document.getElementById('loan-table').innerHTML = tableHtml;
}

/**
 * E. Goal Planner & Retirement Calculator
 */
function calcGoal() {
  const targetCorpus = parseFloat(document.getElementById('goal-target').value) || 0;
  const years = parseFloat(document.getElementById('goal-years').value) || 0;
  const annualRate = parseFloat(document.getElementById('goal-rate').value) || 0;
  
  const inflationToggle = document.getElementById('goal-inflation-toggle').checked;
  const inflationRate = inflationToggle ? parseFloat(document.getElementById('goal-inflation').value) || 0 : 0;

  const stepUpToggle = document.getElementById('goal-stepup-toggle').checked;
  const stepUpRate = stepUpToggle ? parseFloat(document.getElementById('goal-stepup').value) || 0 : 0;

  const monthlyRate = annualRate / 12 / 100;
  const totalMonths = years * 12;

  // 1. Calculate future inflated target corpus
  const inflationAdjustmentFactor = Math.pow(1 + inflationRate / 100, years);
  const inflatedTarget = targetCorpus * inflationAdjustmentFactor;

  // 2. Solve for starting Monthly SIP using simulation / numeric matching (since step-up makes mathematical formulas complex)
  // Let's use simple secant method/binary search to solve for 'P' (initial monthly SIP)
  // which satisfies: FutureValue(P) = inflatedTarget
  
  let low = 0;
  let high = inflatedTarget;
  let startingSIP = 0;
  let achievedFV = 0;
  let totalInvested = 0;

  // Binary search for exact starting monthly SIP
  for (let iter = 0; iter < 50; iter++) {
    startingSIP = (low + high) / 2;
    
    // Simulate SIP build up
    let tempFV = 0;
    let tempInvested = 0;
    let tempSIP = startingSIP;

    for (let m = 1; m <= totalMonths; m++) {
      if (stepUpToggle && m > 1 && (m - 1) % 12 === 0) {
        tempSIP = tempSIP * (1 + stepUpRate / 100);
      }
      tempInvested += tempSIP;
      tempFV = (tempFV + tempSIP) * (1 + monthlyRate);
    }

    achievedFV = tempFV;
    totalInvested = tempInvested;

    if (Math.abs(achievedFV - inflatedTarget) < 1) {
      break;
    } else if (achievedFV < inflatedTarget) {
      low = startingSIP;
    } else {
      high = startingSIP;
    }
  }

  const interestEarned = Math.max(0, inflatedTarget - totalInvested);

  // Update UI values
  document.getElementById('goal-kpi-sip').textContent = formatCurrency(startingSIP);
  document.getElementById('goal-kpi-inflated').textContent = formatCurrency(inflatedTarget);
  document.getElementById('goal-kpi-invested').textContent = formatCurrency(totalInvested);
  document.getElementById('goal-kpi-earnings').textContent = formatCurrency(interestEarned);

  // Display inflation alert
  const goalAlertContainer = document.getElementById('goal-alert-container');
  if (inflationToggle && inflationRate > 0) {
    goalAlertContainer.innerHTML = `
      <div class="alert alert-warning">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <div>
          <div class="alert-title">Inflation Impact Alert</div>
          <div class="alert-description">Due to <strong>${inflationRate}%</strong> inflation, the target corpus value of <strong>${formatCurrency(targetCorpus)}</strong> today increases to <strong>${formatCurrency(inflatedTarget)}</strong> in ${years} years to retain equivalent purchasing power.</div>
        </div>
      </div>
    `;
  } else {
    goalAlertContainer.innerHTML = '';
  }

  // Draw Chart
  renderDoughnutChart('goal-chart', ['Total Invested', 'Growth Needed'], [totalInvested, interestEarned], ['#818cf8', '#10b981']);

  // Render Table
  let tableHtml = `
    <table>
      <thead>
        <tr>
          <th>Year</th>
          <th>Monthly SIP</th>
          <th>Total Invested</th>
          <th>Target Growth Progress</th>
          <th>Target Gap Remaining</th>
        </tr>
      </thead>
      <tbody>
  `;

  let currentSIP = startingSIP;
  let cumInvested = 0;
  let tempFV = 0;

  for (let y = 1; y <= years; y++) {
    for (let m = 1; m <= 12; m++) {
      cumInvested += currentSIP;
      tempFV = (tempFV + currentSIP) * (1 + monthlyRate);
    }

    const gap = Math.max(0, inflatedTarget - tempFV);

    tableHtml += `
      <tr>
        <td>Year ${y}</td>
        <td>${formatCurrency(currentSIP)}</td>
        <td>${formatCurrency(cumInvested)}</td>
        <td>${formatCurrency(tempFV)}</td>
        <td>${gap > 0 ? formatCurrency(gap) : 'Goal Achieved!'}</td>
      </tr>
    `;

    if (stepUpToggle) {
      currentSIP = currentSIP * (1 + stepUpRate / 100);
    }
  }

  tableHtml += `</tbody></table>`;
  document.getElementById('goal-table').innerHTML = tableHtml;
}

/**
 * 5. CHART UTILITY FUNCTIONS (CHART.JS BINDINGS)
 */

function renderDoughnutChart(canvasId, labels, data, colors) {
  // Destroy existing chart if it exists to prevent overlapping draw bugs
  if (charts[canvasId]) {
    charts[canvasId].destroy();
  }

  const ctx = document.getElementById(canvasId).getContext('2d');
  charts[canvasId] = new Chart(ctx, {
    type: 'doughnut',
    data: {
      labels: labels,
      datasets: [{
        data: data,
        backgroundColor: colors,
        borderWidth: 2,
        borderColor: '#ffffff',
        hoverOffset: 4
      }]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: {
          position: 'bottom',
          labels: {
            font: {
              family: 'Inter',
              size: 12,
              weight: 500
            },
            color: '#475569',
            usePointStyle: true,
            padding: 20
          }
        },
        tooltip: {
          backgroundColor: '#0f172a',
          titleFont: { family: 'Outfit', size: 14, weight: 600 },
          bodyFont: { family: 'Inter', size: 13 },
          padding: 12,
          cornerRadius: 8,
          callbacks: {
            label: function(context) {
              return ` ${context.label}: ${formatCurrency(context.raw)}`;
            }
          }
        }
      },
      cutout: '65%'
    }
  });
}

function renderLineChart(canvasId, labels, datasetsConfig) {
  if (charts[canvasId]) {
    charts[canvasId].destroy();
  }

  const ctx = document.getElementById(canvasId).getContext('2d');
  
  const datasets = datasetsConfig.map(cfg => {
    // Generate soft gradient fill
    const gradient = ctx.createLinearGradient(0, 0, 0, 300);
    gradient.addColorStop(0, hexToRgba(cfg.color, 0.15));
    gradient.addColorStop(1, hexToRgba(cfg.color, 0.00));

    return {
      label: cfg.label,
      data: cfg.data,
      borderColor: cfg.color,
      borderWidth: 3,
      backgroundColor: gradient,
      fill: true,
      tension: 0.35,
      pointBackgroundColor: cfg.color,
      pointBorderColor: '#ffffff',
      pointBorderWidth: 1.5,
      pointRadius: 3,
      pointHoverRadius: 6
    };
  });

  charts[canvasId] = new Chart(ctx, {
    type: 'line',
    data: {
      labels: labels,
      datasets: datasets
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: {
          position: 'top',
          labels: {
            font: { family: 'Inter', size: 12, weight: 500 },
            color: '#475569',
            usePointStyle: true,
            padding: 15
          }
        },
        tooltip: {
          backgroundColor: '#0f172a',
          titleFont: { family: 'Outfit', size: 13, weight: 600 },
          bodyFont: { family: 'Inter', size: 12 },
          padding: 12,
          cornerRadius: 8,
          callbacks: {
            label: function(context) {
              return ` ${context.dataset.label}: ${formatCurrency(context.raw)}`;
            }
          }
        }
      },
      scales: {
        x: {
          grid: { display: false },
          ticks: {
            font: { family: 'Inter', size: 11 },
            color: '#94a3b8'
          }
        },
        y: {
          grid: { color: '#f1f5f9' },
          ticks: {
            font: { family: 'Inter', size: 11 },
            color: '#94a3b8',
            callback: function(value) {
              if (value >= 10000000) return `₹${(value / 10000000).toFixed(1)}Cr`;
              if (value >= 100000) return `₹${(value / 100000).toFixed(0)}L`;
              if (value >= 1000) return `₹${(value / 1000).toFixed(0)}K`;
              return `₹${value}`;
            }
          }
        }
      }
    }
  });
}

// Helper to convert hex to rgba
function hexToRgba(hex, alpha) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}
